'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { StrategyBuilder } from '@/components/strategy/StrategyBuilder';
import { BacktestConfigPanel } from '@/components/strategy/BacktestConfig';
import { StrategyConfig, BacktestConfig } from '@/types/strategy';
import { backendApi } from '@/lib/backend-api';

// Generate Python code template based on strategy type and parameters
function generateStrategyCode(type: string, parameters: Record<string, any>): string {
    const paramsStr = Object.entries(parameters)
        .map(([key, value]) => `        self.${key} = ${JSON.stringify(value)}`)
        .join('\n');

    return `# Auto-generated strategy code
# Strategy Type: ${type}

from hummingbot.strategy.script_strategy_base import ScriptStrategyBase
from decimal import Decimal

class ${type.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('')}Strategy(ScriptStrategyBase):
    """
    ${type.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())} Strategy
    Generated by H-Bot UI
    """
    
    def __init__(self, connectors):
        super().__init__(connectors)
${paramsStr || '        pass'}
    
    def on_tick(self):
        # Main strategy logic runs here
        pass
    
    def did_complete_buy_order(self, order_completed_event):
        pass
    
    def did_complete_sell_order(self, order_completed_event):
        pass
`;
}

export default function NewStrategyPage() {
    const router = useRouter();
    const [activeTab, setActiveTab] = useState<'build' | 'backtest'>('build');
    const [strategy, setStrategy] = useState<StrategyConfig | null>(null);
    const [isBacktesting, setIsBacktesting] = useState(false);
    const [isSaving, setIsSaving] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const handleSaveStrategy = async (config: StrategyConfig) => {
        setIsSaving(true);
        setError(null);

        try {
            // Generate code template based on strategy type
            const code = generateStrategyCode(config.type, config.parameters);

            // Create strategy payload for backend
            const payload = {
                name: config.name.toLowerCase().replace(/\s+/g, '_'),
                description: config.description || `${config.type} strategy`,
                code: code,
                config: {
                    type: config.type,
                    parameters: config.parameters
                }
            };

            // Call backend API
            const response = await backendApi.post('/strategies', payload);

            if (response.data.status === 'success') {
                // Save locally for backtest tab
                setStrategy(config);
                // Redirect to strategy detail page
                router.push(`/strategies/${payload.name}`);
            } else {
                throw new Error(response.data.error || 'Failed to create strategy');
            }
        } catch (err) {
            console.error('Error saving strategy:', err);
            setError(err instanceof Error ? err.message : 'Failed to save strategy');
            // Still save locally so user can try again
            setStrategy(config);
        } finally {
            setIsSaving(false);
        }
    };

    const handleRunBacktest = async (config: BacktestConfig) => {
        setIsBacktesting(true);
        console.log('Running backtest with:', config);

        // Simulate backtest
        await new Promise(resolve => setTimeout(resolve, 3000));

        setIsBacktesting(false);
        alert('Backtest completed! (Simulation)');
    };

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-2xl font-bold text-white">Strategy Studio</h1>
                    <p className="text-slate-400 mt-1">Design, configure, and backtest your trading strategies</p>
                </div>

                <div className="flex bg-gray-900 rounded-lg p-1 border border-gray-800">
                    <button
                        onClick={() => setActiveTab('build')}
                        className={`px-4 py-2 rounded-md text-sm font-medium transition-colors ${activeTab === 'build'
                            ? 'bg-blue-600 text-white'
                            : 'text-gray-400 hover:text-white'
                            }`}
                    >
                        Builder
                    </button>
                    <button
                        onClick={() => setActiveTab('backtest')}
                        disabled={!strategy}
                        className={`px-4 py-2 rounded-md text-sm font-medium transition-colors ${activeTab === 'backtest'
                            ? 'bg-blue-600 text-white'
                            : 'text-gray-400 hover:text-white disabled:opacity-50 disabled:cursor-not-allowed'
                            }`}
                    >
                        Backtest
                    </button>
                </div>
            </div>

            {/* Error message */}
            {error && (
                <div className="bg-red-900/20 border border-red-900 rounded-lg p-4">
                    <p className="text-red-400">Error: {error}</p>
                </div>
            )}

            {/* Saving indicator */}
            {isSaving && (
                <div className="bg-blue-900/20 border border-blue-900 rounded-lg p-4 flex items-center gap-3">
                    <div className="animate-spin w-5 h-5 border-2 border-blue-500 border-t-transparent rounded-full" />
                    <p className="text-blue-400">Saving strategy to backend...</p>
                </div>
            )}

            {activeTab === 'build' && (
                <StrategyBuilder
                    initialConfig={strategy || undefined}
                    onSave={handleSaveStrategy}
                />
            )}

            {activeTab === 'backtest' && strategy && (
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                    <div className="lg:col-span-1">
                        <BacktestConfigPanel
                            strategyId={strategy.id}
                            onRunBacktest={handleRunBacktest}
                            isRunning={isBacktesting}
                        />
                    </div>
                    <div className="lg:col-span-2 bg-gray-900 rounded-xl border border-gray-800 p-6 flex items-center justify-center text-gray-500">
                        {isBacktesting ? (
                            <div className="text-center space-y-4">
                                <div className="animate-spin w-8 h-8 border-2 border-blue-500 border-t-transparent rounded-full mx-auto"></div>
                                <p>Running simulation on historical data...</p>
                            </div>
                        ) : (
                            <p>Run a backtest to see results here</p>
                        )}
                    </div>
                </div>
            )}
        </div>
    );
}
